import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage();
await p.goto("http://127.0.0.1:5173/");
await p.waitForTimeout(1000);
await p.getByPlaceholder("What do you want the AI team to do?").fill("sandbox_code_fix");
await p.getByText("Advanced").click();
await p.getByPlaceholder("sample-python").fill("sample-python");
await p.getByRole("button", { name: "Start Task" }).click();
await p.waitForURL(/\/tasks\/[0-9a-f]+/, { timeout: 30000 });
const approve = p.getByRole("button", { name: "Approve" });
await approve.first().waitFor({ timeout: 60000 });
await approve.first().click();
await p.waitForTimeout(5000);
console.log(await p.locator("body").innerText());
await b.close();
