import { chromium } from "@playwright/test";
import { mkdirSync } from "fs";
mkdirSync("e2e/shots", { recursive: true });
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 860 } });
await p.goto("http://127.0.0.1:5173/");
await p.waitForTimeout(2500);
await p.screenshot({ path: "e2e/shots/dashboard.png", fullPage: false });
await p.goto("http://127.0.0.1:5173/agents");
await p.waitForTimeout(1200);
await p.screenshot({ path: "e2e/shots/agents.png" });
await p.goto("http://127.0.0.1:5173/tools");
await p.waitForTimeout(1200);
await p.screenshot({ path: "e2e/shots/tools.png" });
await p.goto("http://127.0.0.1:5173/settings");
await p.waitForTimeout(1500);
await p.screenshot({ path: "e2e/shots/settings.png" });
await p.goto("http://127.0.0.1:5173/evidence");
await p.waitForTimeout(1500);
await p.screenshot({ path: "e2e/shots/evidence.png" });
await p.goto("http://127.0.0.1:5173/memory");
await p.waitForTimeout(1000);
await p.screenshot({ path: "e2e/shots/memory.png" });
await b.close();
console.log("shots done");
